//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CovidAppMVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Covid19Entities : DbContext
    {
        public Covid19Entities()
            : base("name=Covid19Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Администраторы> Администраторы { get; set; }
        public virtual DbSet<Квалификации> Квалификации { get; set; }
        public virtual DbSet<Отделы_организации> Отделы_организации { get; set; }
        public virtual DbSet<Пол> Пол { get; set; }
        public virtual DbSet<Сертификаты> Сертификаты { get; set; }
        public virtual DbSet<Сотрудники> Сотрудники { get; set; }
        public virtual DbSet<Типы_сертификатов> Типы_сертификатов { get; set; }
        public virtual DbSet<Участки_организации> Участки_организации { get; set; }
    }
}
