//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CovidAppMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Сертификаты
    {
        public int Код_сертификата { get; set; }
        public string Номер_сертификата { get; set; }
        public System.DateTime Дата_начала_действия { get; set; }
        public System.DateTime Дата_окончания_действия { get; set; }
        public int Код_сотрудника { get; set; }
        public int Код_типа_сертификата { get; set; }
    
        public virtual Сотрудники Сотрудники { get; set; }
        public virtual Типы_сертификатов Типы_сертификатов { get; set; }
    }
}
