//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CovidAppMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Сотрудники
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Сотрудники()
        {
            this.Администраторы = new HashSet<Администраторы>();
            this.Сертификаты = new HashSet<Сертификаты>();
        }
    
        public int Код_сотрудника { get; set; }
        public string ФИО_сотрудника { get; set; }
        public System.DateTime Дата_рождения { get; set; }
        public int Код_пола { get; set; }
        public string Серия_номер_паспорта { get; set; }
        public string Email { get; set; }
        public int Код_участка { get; set; }
        public int Код_квалификации { get; set; }
        public bool Администратор { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Администраторы> Администраторы { get; set; }
        public virtual Квалификации Квалификации { get; set; }
        public virtual Пол Пол { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Сертификаты> Сертификаты { get; set; }
        public virtual Участки_организации Участки_организации { get; set; }
    }
}
