//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CovidAppMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Типы_сертификатов
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Типы_сертификатов()
        {
            this.Сертификаты = new HashSet<Сертификаты>();
        }
    
        public int Код_типа_сертификата { get; set; }
        public string Тип_сертификата { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Сертификаты> Сертификаты { get; set; }
    }
}
